name: 'API Service - Merge to main'

on:
  pull_request:

jobs:
  update-version-and-create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our code
        uses: actions/checkout@v3
        id: checkout
        with:
          fetch-depth: 0
      - name: Echo
        uses: gentleseal/action-conventional-commits@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-commit-types: >
            [
              "feat",
              "fix",
              "docs"
            ]